import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LANGUAGE_STORAGE_KEY = 'app_language';

const translations = {
  en: {
    app_name: 'Football Field Booking',
    nav_home: 'Home',
    nav_fields: 'Fields',
    nav_league: 'League',
    nav_leagues: 'Leagues',
    nav_teams: 'Teams',
    nav_login: 'Login',
    nav_register: 'Register',
    nav_dashboard: 'Dashboard',
    nav_bookings: 'Bookings',
    nav_matches: 'Matches',
    nav_open_matches: 'Open Matches',
    nav_profile: 'Profile',
    nav_notifications: 'Notifications',
    nav_analytics: 'Analytics',
    nav_my_fields: 'My Fields',
    nav_booking_requests: 'Booking Requests',
    nav_manage_users: 'Manage Users',
    nav_role_requests: 'Role Requests',
    nav_settings: 'Settings',
    action_logout: 'Logout',
    action_go_dashboard: 'Go to Dashboard',
    action_add_field: 'Add field',
    action_review_requests: 'Review requests',
    action_manage_fields: 'Manage fields',
    action_go_to_requests: 'Go to requests',
    action_edit: 'Edit',
    action_confirm: 'Confirm',
    action_decline: 'Decline',
    action_cancel: 'Cancel',
    action_back: 'Back',
    action_back_to_fields: 'Back to Fields',
    action_back_to_bookings: 'Back to Bookings',
    action_book_now: 'Book Now',
    action_open_settings: 'Open Settings',
    action_create_team: 'Create Team',
    workspace_player: 'Player & Captain Panel',
    workspace_owner: 'Field Owner Panel',
    label_workspace: 'Workspace',
    label_language: 'Language',
    language_en: 'English',
    language_km: 'Khmer',
    role_user: 'User',
    role_player: 'Player',
    role_field_owner: 'Field Owner',
    page_dashboard_subtitle: 'Overview of your activity and updates',
    page_fields_subtitle: 'Browse and discover available football fields',
    page_league_subtitle: 'Track fixtures, results, and standings',
    page_teams_subtitle: 'Manage your team and membership requests',
    page_bookings_subtitle: 'Create and manage your field bookings',
    page_open_matches_subtitle: 'Find and respond to open opponent matches',
    page_notifications_subtitle: 'Review invitations and request updates',
    page_profile_subtitle: 'Update your account and preferences',
    page_settings_subtitle: 'Manage account preferences and role requests',
    page_manage_users_subtitle: 'Admin user management area',
    page_role_requests_subtitle: 'Review pending role access requests',
    owner_badge: 'Field Owner',
    owner_dashboard_title: 'Owner Dashboard',
    owner_dashboard_subtitle: 'Track your fields, review booking requests, and keep your schedule under control.',
    owner_pending_title: 'Pending booking requests',
    owner_pending_subtitle: 'Approve or reject new requests from teams.',
    owner_pending_empty_title: 'No pending requests',
    owner_pending_empty_description: 'When players create bookings for your fields, they will show up here.',
    owner_upcoming_title: 'Upcoming confirmed',
    owner_upcoming_subtitle: 'Your next scheduled bookings after approval.',
    owner_upcoming_empty_title: 'No upcoming bookings',
    owner_upcoming_empty_description: 'Confirm pending requests to see your upcoming schedule.',
    owner_my_fields_title: 'My fields',
    owner_my_fields_subtitle: 'Your venues, availability, and pricing at a glance.',
    owner_no_fields_title: 'No fields yet',
    owner_no_fields_description: 'Create your first field to start receiving booking requests.',
    owner_completed_summary: 'Completed bookings: {{count}}. Revenue estimate includes owner-approved bookings, even if they are cancelled later.',
    owner_pending_count: '{{count}} pending',
    owner_upcoming_count: '{{count}} upcoming',
    stat_my_fields: 'My Fields',
    stat_pending_requests: 'Pending Requests',
    stat_confirmed: 'Confirmed',
    stat_revenue_est: 'Revenue (est.)',
    booking_status_confirmed: 'confirmed'
    ,
    common_all: 'All',
    common_pending: 'Pending',
    common_confirmed: 'Confirmed',
    common_completed: 'Completed',
    common_cancelled: 'Cancelled',
    common_loading: 'Loading...',
    common_updating: 'Updating...',
    common_created: 'Created',
    common_unknown: 'Unknown',
    fields_title: 'Fields',
    fields_subtitle: 'Browse football fields near you.',
    fields_results: '{{count}} results',
    fields_search: 'Search',
    fields_search_placeholder: 'Search fields...',
    fields_filter_type: 'Field Type',
    fields_filter_surface: 'Surface Type',
    fields_filter_price: 'Max Price/Hour',
    fields_all_types: 'All Types',
    fields_all_surfaces: 'All Surfaces',
    fields_no_rating: 'No rating',
    fields_reviews: '{{count}} reviews',
    fields_delete_title: 'Delete Field',
    fields_message_to_owner: 'Message to owner',
    fields_booking_access_required: 'Booking access is required.',
    fields_booking_access_title: 'Booking Access',
    fields_only_available: 'Only fields with status "available" can be booked.',
    booking_title: 'Bookings',
    booking_subtitle_manage: 'Manage your football field bookings',
    booking_subtitle_track: 'Track your bookings here.',
    booking_new: 'New Booking',
    booking_request_captain: 'Request Captain Access',
    booking_filter_status: 'Status',
    booking_filter_opponent: 'Opponent Match',
    booking_open_for_opponents: 'Open for Opponents',
    booking_not_open: 'Not Open',
    booking_cancel_confirm: 'Do you want to cancel your booking?',
    booking_cancel_title: 'Cancel Booking',
    booking_cancel_button: 'Cancel Booking',
    booking_complete: 'Complete',
    booking_matched: 'Matched',
    booking_join_requests: 'Join Requests',
    booking_no_requests: 'No requests yet.',
    booking_loading_requests: 'Loading requests...',
    booking_booked_by: 'Booked by',
    booking_unknown_field: 'Unknown Field',
    booking_no_team: 'No team',
    booking_waiting_owner_approval: 'Waiting for owner approval. This slot is still open until confirmed.',
    booking_already_matched: 'Already matched',
    booking_team_a: 'Team A',
    booking_cancelling_match: 'Cancelling Match...',
    booking_cancel_matched_opponent: 'Cancel Matched Opponent',
    booking_open_match: 'Open Match',
    booking_close_match: 'Close Match',
    booking_unknown_team: 'Unknown team',
    booking_unknown_captain: 'Unknown captain',
    booking_approve_join: 'Approve Join',
    booking_empty_title: 'No bookings found',
    booking_empty_create_first: 'Create your first booking to get started.',
    booking_empty_request_captain: 'Please request to become captain in Settings.',
    booking_empty_filtered: 'No bookings found for the selected filters.',
    team_captain: 'Captain',
    create_booking_access_required: 'Access Required',
    create_booking_access_description: 'You need captain, field owner, or admin access to book fields.',
    create_booking_title: 'Create New Booking',
    create_booking_subtitle: 'Book a football field for your team',
    create_booking_select_field: 'Select Field *',
    create_booking_select_team: 'Select Team *',
    create_booking_choose_field: 'Choose a field...',
    create_booking_choose_team: 'Choose a team...',
    create_booking_jersey_colors: 'Jersey Colors',
    create_booking_need_team: 'You need a team before booking.',
    create_booking_start_time: 'Start Time *',
    create_booking_duration: 'Duration *',
    create_booking_notes: 'Notes',
    create_booking_notes_placeholder: 'Add any booking notes...',
    create_booking_summary: 'Booking Summary',
    create_booking_field: 'Field',
    create_booking_team: 'Team',
    create_booking_date_time: 'Date & Time',
    create_booking_total_price: 'Total Price',
    create_booking_field_details: 'Field Details for Captain',
    create_booking_field_type: 'Field Type',
    create_booking_surface: 'Surface',
    create_booking_capacity: 'Capacity',
    create_booking_amenities: 'Amenities',
    create_booking_no_amenities: 'No amenities listed for this field.',
    create_booking_submit: 'Create Booking',
    create_booking_submitting: 'Creating Booking...',
    create_booking_success: 'Booking created successfully!',
    create_booking_valid_datetime: 'Please provide a valid date and time',
    field_not_found: 'Field not found',
    field_not_found_description: 'The field may have been removed or the link is incorrect.',
    field_not_available: 'Not Available',
    field_request_access: 'Request Booking Access',
    field_overview: 'Overview',
    field_live_booking: 'Live Booking',
    field_comment_rate: 'Comment & Rate',
    field_about: 'About This Field',
    field_ready_description: 'This field is ready for bookings, team play, and regular matches.',
    field_name: 'Field Name',
    field_type: 'Field Type',
    field_surface_type: 'Surface Type',
    field_price_per_hour: 'Price Per Hour',
    field_discount: 'Discount',
    field_capacity: 'Capacity',
    field_status: 'Status',
    field_full_address: 'Full Address',
    field_address_not_specified: 'Address not specified',
    field_coordinates: 'Coordinates: {{lat}}, {{lng}}',
    field_location_map: 'Location Map',
    field_amenities: 'Amenities',
    field_live_schedule: 'Live Booking Schedule',
    field_live_schedule_subtitle: 'Visual schedule for this field only. See who is playing when.',
    field_select_day: 'Select Day',
    field_schedule: 'Field schedule',
    field_schedule_subtitle: 'Only this field is shown. Captains can book available slots.',
    field_available: 'Available',
    field_booked: 'Booked',
    field_available_slot: 'Available - click to book',
    field_available_open: 'Open for booking on this field.',
    field_reserved_slot: 'Reserved slot',
    field_pending_request: 'Pending request on this field.',
    field_confirmed_booking: 'Confirmed booking on this field.',
    field_reviews_coming: 'Reviews will appear here',
    field_reviews_placeholder: 'Field comments and rating submissions can be shown in this section after review data is connected for this page.',
    not_specified: 'Not specified',
    players_suffix: '{{count}} players',
    hour_suffix: '{{value}} hour',
    hours_suffix: '{{value}} hours',
    login_badge: 'Account Access',
    login_title: 'Sign In',
    login_description: 'Welcome back. Sign in to continue managing your bookings, teams, and football activity.',
    login_no_account: "Don't have an account?",
    login_create_one: 'Create one here',
    login_email_label: 'Email Address',
    login_email_placeholder: 'you@example.com',
    login_password_label: 'Password',
    login_password_placeholder: 'Password',
    login_hide_password: 'Hide password',
    login_show_password: 'Show password',
    login_remember_me: 'Remember me',
    login_forgot_password: 'Forgot password?',
    login_forgot_not_ready: 'Forgot password is not implemented yet.',
    login_not_available_title: 'Not Available Yet',
    login_signing_in: 'Signing in...',
    login_browse_first: 'Want to browse first?',
    login_continue_guest: 'Continue as guest',
    login_validation_email: 'Please enter your email address.',
    login_validation_password: 'Please enter your password.',
    register_badge: 'New Account',
    register_title: 'Create Account',
    register_description: 'Create your account to start booking fields, joining teams, or managing your venue with a clean and simple setup.',
    register_already_have_account: 'Already have an account?',
    register_sign_in: 'Sign in',
    register_first_name: 'First name',
    register_last_name: 'Last name',
    register_username: 'Username',
    register_phone: 'Phone',
    register_email: 'Email',
    register_password: 'Password',
    register_confirm_password: 'Confirm password',
    register_password_hint: 'Use at least 8 characters.',
    register_update_later: 'You can update your profile later',
    register_creating: 'Creating...',
    register_validation_first_name: 'Please enter your first name.',
    register_validation_last_name: 'Please enter your last name.',
    register_validation_username: 'Please enter your username.',
    register_validation_email: 'Please enter your email address.',
    register_validation_password: 'Please enter your password.',
    register_validation_confirm_password: 'Please confirm your password.',
    register_passwords_no_match: 'Passwords do not match.',
    settings_account_center: 'Account Center',
    settings_intro: 'This page now groups the things people usually expect in settings: account overview, device preferences, security, and access requests.',
    settings_preferences: 'Preferences',
    settings_preferences_desc: 'Small quality-of-life options that make the app feel more personal. These are saved on this device.',
    settings_local_only: 'Local only',
    settings_email_updates: 'Email updates',
    settings_email_updates_desc: 'Keep important account updates and approval decisions enabled.',
    settings_booking_reminders: 'Booking reminders',
    settings_booking_reminders_desc: 'Show reminders for upcoming bookings and pending field confirmations.',
    settings_match_alerts: 'Match and invite alerts',
    settings_match_alerts_desc: 'Prioritize team invites, join requests, and open match activity.',
    settings_compact_layout: 'Compact layout',
    settings_compact_layout_desc: 'Use tighter spacing for tables and content-heavy pages.',
    settings_language_desc: 'Change the interface language for this browser session.',
    settings_start_page: 'Default start page',
    settings_start_page_desc: 'Choose the first area you want to land on when you open the app.',
    settings_access_requests: 'Access Requests',
    settings_access_requests_desc: 'Upgrade your account when you need more control, like creating field bookings, team management, or field administration.',
    settings_request_history: 'Request History',
    settings_request_history_desc: 'A quick timeline of your previous access requests and their review status.',
    settings_security: 'Security',
    settings_security_desc: 'Keep your account protected and review the actions that affect sign-in.',
    settings_password: 'Password',
    settings_password_desc: 'Change your password any time if you shared a device, reused an old password, or just want a stronger one.',
    settings_change_password: 'Change Password',
    settings_current_account_role: 'Current account role',
    settings_last_review: 'Last settings review',
    settings_quick_links: 'Quick Links',
    settings_quick_links_desc: 'Shortcut actions people usually look for while managing their account.',
    settings_current_role: 'Current role',
    settings_captain_access: 'Captain Access',
    settings_captain_access_desc: 'Create field bookings, manage team members, approve join requests, and organize open matches.',
    settings_owner_access: 'Field Owner Access',
    settings_owner_access_desc: 'Create fields, manage booking requests, and control your venue schedule.',
    settings_member_since: 'Member since',
    settings_pending_requests: 'Pending requests',
    settings_available_upgrades: 'Available upgrades',
    settings_profile_details: 'Profile details',
    settings_profile_details_desc: 'Update your photo and personal information.',
    settings_notifications_desc: 'Review invites, alerts, and unread updates.',
    settings_pending_review: 'Pending review',
    settings_request_again: 'Request again',
    settings_request_role_button: 'Request {{role}}',
    settings_submitting: 'Submitting...',
    settings_deleting: 'Deleting...',
    settings_delete_request: 'Delete Request',
    settings_what_belongs: 'What belongs here?',
    settings_what_belongs_desc: 'Usually: security, notifications, app preferences, support, and role or permission requests. That structure is what this page now follows.',
    settings_change_password_desc: 'Enter your current password and choose a new one.',
    settings_close_password_form: 'Close change password form',
    settings_current_password: 'Current Password',
    settings_new_password: 'New Password',
    settings_confirm_new_password: 'Confirm New Password',
    settings_hide_current_password: 'Hide current password',
    settings_show_current_password: 'Show current password',
    settings_hide_new_password: 'Hide new password',
    settings_show_new_password: 'Show new password',
    settings_hide_password_confirmation: 'Hide password confirmation',
    settings_show_password_confirmation: 'Show password confirmation',
    settings_changing_password: 'Changing...',
    settings_save_password: 'Save Password',
    profile_admin: 'Admin Profile',
    profile_owner: 'Owner Profile',
    profile_account: 'Account Profile',
    profile_unknown_user: 'Unknown User',
    profile_guest: 'guest',
    profile_edit: 'Edit Profile',
    profile_remove_photo: 'Remove Photo',
    profile_admin_tools: 'Admin Tools',
    profile_admin_shortcuts: 'Administration Shortcuts',
    profile_admin_shortcuts_desc: 'Quick links for the areas you manage most often.',
    profile_manage_users_desc: 'Review and manage user accounts.',
    profile_role_requests_desc: 'Approve or reject access changes.',
    profile_account_status: 'Account Status',
    profile_active: 'active',
    profile_personal_info: 'Personal Information',
    profile_full_name: 'Full Name',
    profile_not_specified: 'Not specified',
    profile_dob: 'Date of Birth',
    profile_address: 'Address',
    profile_account_stats: 'Account Statistics',
    profile_total_bookings: 'Total Bookings',
    profile_current_teams: 'Current Teams',
    profile_no_teams: 'You are not in any team yet.',
    profile_no_home_field: 'No home field assigned',
    profile_members_count: '{{count}} members',
    profile_view_team: 'View team',
    profile_photo: 'Profile photo',
    profile_edit_message: 'Update your account information below.',
    profile_saving: 'Saving...',
    profile_save_changes: 'Save Changes',
    profile_enter_first_name: 'Enter first name',
    profile_enter_last_name: 'Enter last name',
    profile_enter_email: 'Enter email address',
    profile_phone_number: 'Phone Number',
    profile_enter_phone: 'Enter phone number',
    profile_gender: 'Gender',
    profile_gender_male: 'Male',
    profile_gender_female: 'Female',
    profile_gender_other: 'Other',
    profile_enter_address: 'Enter address',
    teams_all: 'All Teams',
    teams_my: 'My Teams',
    teams_admin_desc: 'Admin view of all teams. You can open or delete any team.',
    teams_my_desc: 'View your active teams and manage membership requests if you are a captain.',
    teams_results: '{{count}} results',
    teams_browse: 'Browse Teams',
    teams_invitations: 'Team Invitations',
    teams_pending_count: '{{count}} pending',
    teams_invited_by: 'Invited by: {{name}}',
    teams_captain: 'Captain',
    teams_accept: 'Accept',
    teams_decline: 'Decline',
    teams_no_description: 'No description available.',
    teams_captain_label: 'Captain: {{name}}',
    teams_home_field: 'Home Field: {{name}}',
    teams_skill: 'Skill:',
    teams_jersey: 'Jersey:',
    teams_view_details: 'View Details',
    teams_delete: 'Delete',
    teams_none_found: 'No teams found',
    teams_none_found_desc: 'Browse teams to request to join, or create your own team if you are a captain.',
    teams_delete_modal_title: 'Delete Team',
    teams_delete_modal_desc: 'Send a message to captain before deleting {{team}}.',
    teams_message_to_captain: 'Message to captain',
    teams_delete_reason_placeholder: 'Explain why this team is being deleted...',
    teams_send_delete: 'Send & Delete',
    teams_image: 'Team image',
    league_title: 'Football Leagues',
    league_subtitle: 'Live scores and standings',
    league_table: 'Table',
    league_loading: 'Loading league data...',
    league_yesterday: 'Yesterday',
    league_today: 'Today',
    league_tomorrow: 'Tomorrow',
    league_latest_matches: 'Latest Matches',
    league_no_matches_date: 'No matches for this date.',
    league_table_title: 'League Table',
    league_form: 'Form',
    league_full_time: 'Full Time',
    league_live: 'Live',
    league_postponed: 'Postponed',
    league_upcoming: 'Upcoming'
  },
  km: {
    app_name: 'ការកក់ទីលានបាល់ទាត់',
    nav_home: 'ទំព័រដើម',
    nav_fields: 'ទីលាន',
    nav_league: 'លីគ',
    nav_leagues: 'លីគ',
    nav_teams: 'ក្រុម',
    nav_login: 'ចូលគណនី',
    nav_register: 'ចុះឈ្មោះ',
    nav_dashboard: 'ផ្ទាំងគ្រប់គ្រង',
    nav_bookings: 'ការកក់',
    nav_matches: 'ការប្រកួត',
    nav_open_matches: 'ការប្រកួតបើកចំហ',
    nav_profile: 'ប្រវត្តិរូប',
    nav_notifications: 'ការជូនដំណឹង',
    nav_analytics: 'វិភាគទិន្នន័យ',
    nav_my_fields: 'ទីលានរបស់ខ្ញុំ',
    nav_booking_requests: 'សំណើកក់',
    nav_manage_users: 'គ្រប់គ្រងអ្នកប្រើ',
    nav_role_requests: 'សំណើតួនាទី',
    nav_settings: 'ការកំណត់',
    action_logout: 'ចាកចេញ',
    action_go_dashboard: 'ទៅផ្ទាំងគ្រប់គ្រង',
    action_add_field: 'បន្ថែមទីលាន',
    action_review_requests: 'ពិនិត្យសំណើ',
    action_manage_fields: 'គ្រប់គ្រងទីលាន',
    action_go_to_requests: 'ទៅកាន់សំណើ',
    action_edit: 'កែប្រែ',
    action_confirm: 'យល់ព្រម',
    action_decline: 'បដិសេធ',
    action_cancel: 'បោះបង់',
    action_back: 'ត្រឡប់ក្រោយ',
    action_back_to_fields: 'ត្រឡប់ទៅទីលាន',
    action_back_to_bookings: 'ត្រឡប់ទៅការកក់',
    action_book_now: 'កក់ឥឡូវនេះ',
    action_open_settings: 'បើកការកំណត់',
    action_create_team: 'បង្កើតក្រុម',
    workspace_player: 'ផ្ទាំងអ្នកលេង និងកាពីតែន',
    workspace_owner: 'ផ្ទាំងម្ចាស់ទីលាន',
    label_workspace: 'កន្លែងការងារ',
    label_language: 'ភាសា',
    language_en: 'English',
    language_km: 'ខ្មែរ',
    role_user: 'អ្នកប្រើ',
    role_player: 'អ្នកលេង',
    role_field_owner: 'ម្ចាស់ទីលាន',
    page_dashboard_subtitle: 'សង្ខេបសកម្មភាព និងព័ត៌មានថ្មីៗរបស់អ្នក',
    page_fields_subtitle: 'ស្វែងរក និងមើលទីលានបាល់ទាត់ដែលមាន',
    page_league_subtitle: 'តាមដានកាលវិភាគ លទ្ធផល និងតារាងចំណាត់ថ្នាក់',
    page_teams_subtitle: 'គ្រប់គ្រងក្រុម និងសំណើសមាជិកភាពរបស់អ្នក',
    page_bookings_subtitle: 'បង្កើត និងគ្រប់គ្រងការកក់ទីលានរបស់អ្នក',
    page_open_matches_subtitle: 'ស្វែងរក និងឆ្លើយតបការប្រកួតបើកចំហ',
    page_notifications_subtitle: 'ពិនិត្យការអញ្ជើញ និងបច្ចុប្បន្នភាពសំណើ',
    page_profile_subtitle: 'កែប្រែគណនី និងចំណង់ចំណូលចិត្តរបស់អ្នក',
    page_settings_subtitle: 'គ្រប់គ្រងការកំណត់គណនី និងសំណើតួនាទី',
    page_manage_users_subtitle: 'ផ្ទាំងគ្រប់គ្រងអ្នកប្រើសម្រាប់អ្នកគ្រប់គ្រង',
    page_role_requests_subtitle: 'ពិនិត្យសំណើសុំសិទ្ធិតួនាទីដែលកំពុងរង់ចាំ',
    owner_badge: 'ម្ចាស់ទីលាន',
    owner_dashboard_title: 'ផ្ទាំងម្ចាស់ទីលាន',
    owner_dashboard_subtitle: 'តាមដានទីលានរបស់អ្នក ពិនិត្យសំណើកក់ និងគ្រប់គ្រងកាលវិភាគបានងាយស្រួល។',
    owner_pending_title: 'សំណើកក់កំពុងរង់ចាំ',
    owner_pending_subtitle: 'យល់ព្រម ឬបដិសេធសំណើថ្មីៗពីក្រុម។',
    owner_pending_empty_title: 'មិនមានសំណើកក់កំពុងរង់ចាំ',
    owner_pending_empty_description: 'នៅពេលអ្នកលេងបង្កើតការកក់សម្រាប់ទីលានរបស់អ្នក វានឹងបង្ហាញនៅទីនេះ។',
    owner_upcoming_title: 'ការកក់ដែលបានយល់ព្រមខាងមុខ',
    owner_upcoming_subtitle: 'ការកក់បន្ទាប់របស់អ្នកបន្ទាប់ពីបានអនុម័ត។',
    owner_upcoming_empty_title: 'មិនមានការកក់ខាងមុខ',
    owner_upcoming_empty_description: 'យល់ព្រមសំណើកក់ដែលកំពុងរង់ចាំ ដើម្បីមើលកាលវិភាគខាងមុខ។',
    owner_my_fields_title: 'ទីលានរបស់ខ្ញុំ',
    owner_my_fields_subtitle: 'មើលទីតាំង ភាពទំនេរ និងតម្លៃរបស់ទីលានរបស់អ្នកភ្លាមៗ។',
    owner_no_fields_title: 'មិនទាន់មានទីលាន',
    owner_no_fields_description: 'បង្កើតទីលានដំបូងរបស់អ្នក ដើម្បីចាប់ផ្តើមទទួលសំណើកក់។',
    owner_completed_summary: 'ការកក់បានបញ្ចប់៖ {{count}}។ ប្រាក់ចំណូលប៉ាន់ស្មានរួមបញ្ចូលការកក់ដែលម្ចាស់ទីលានបានយល់ព្រម ទោះបីបោះបង់ពេលក្រោយក៏ដោយ។',
    owner_pending_count: '{{count}} កំពុងរង់ចាំ',
    owner_upcoming_count: '{{count}} ខាងមុខ',
    stat_my_fields: 'ទីលានរបស់ខ្ញុំ',
    stat_pending_requests: 'សំណើកំពុងរង់ចាំ',
    stat_confirmed: 'បានយល់ព្រម',
    stat_revenue_est: 'ប្រាក់ចំណូល (ប៉ាន់ស្មាន)',
    booking_status_confirmed: 'បានយល់ព្រម',
    common_all: 'ទាំងអស់',
    common_pending: 'កំពុងរង់ចាំ',
    common_confirmed: 'បានយល់ព្រម',
    common_completed: 'បានបញ្ចប់',
    common_cancelled: 'បានបោះបង់',
    common_loading: 'កំពុងផ្ទុក...',
    common_updating: 'កំពុងធ្វើបច្ចុប្បន្នភាព...',
    common_created: 'បានបង្កើត',
    common_unknown: 'មិនស្គាល់',
    fields_title: 'ទីលាន',
    fields_subtitle: 'ស្វែងរកទីលានបាល់ទាត់នៅជិតអ្នក។',
    fields_results: '{{count}} លទ្ធផល',
    fields_search: 'ស្វែងរក',
    fields_search_placeholder: 'ស្វែងរកទីលាន...',
    fields_filter_type: 'ប្រភេទទីលាន',
    fields_filter_surface: 'ប្រភេទផ្ទៃ',
    fields_filter_price: 'តម្លៃអតិបរមា/ម៉ោង',
    fields_all_types: 'គ្រប់ប្រភេទ',
    fields_all_surfaces: 'គ្រប់ផ្ទៃ',
    fields_no_rating: 'មិនទាន់មានការវាយតម្លៃ',
    fields_reviews: '{{count}} ការវាយតម្លៃ',
    fields_delete_title: 'លុបទីលាន',
    fields_message_to_owner: 'សារទៅកាន់ម្ចាស់ទីលាន',
    fields_booking_access_required: 'ត្រូវការសិទ្ធិកក់ទីលាន។',
    fields_booking_access_title: 'សិទ្ធិកក់ទីលាន',
    fields_only_available: 'អាចកក់បានតែទីលានដែលមានស្ថានភាព "available" ប៉ុណ្ណោះ។',
    booking_title: 'ការកក់',
    booking_subtitle_manage: 'គ្រប់គ្រងការកក់ទីលានបាល់ទាត់របស់អ្នក',
    booking_subtitle_track: 'តាមដានការកក់របស់អ្នកនៅទីនេះ។',
    booking_new: 'ការកក់ថ្មី',
    booking_request_captain: 'ស្នើសុំសិទ្ធិកាពីតែន',
    booking_filter_status: 'ស្ថានភាព',
    booking_filter_opponent: 'ការប្រកួតគូប្រជែង',
    booking_open_for_opponents: 'បើកសម្រាប់គូប្រជែង',
    booking_not_open: 'មិនបើក',
    booking_cancel_confirm: 'តើអ្នកចង់បោះបង់ការកក់របស់អ្នកមែនទេ?',
    booking_cancel_title: 'បោះបង់ការកក់',
    booking_cancel_button: 'បោះបង់ការកក់',
    booking_complete: 'បញ្ចប់',
    booking_matched: 'បានផ្គូផ្គង',
    booking_join_requests: 'សំណើចូលរួម',
    booking_no_requests: 'មិនទាន់មានសំណើ។',
    booking_loading_requests: 'កំពុងផ្ទុកសំណើ...',
    booking_booked_by: 'កក់ដោយ',
    booking_unknown_field: 'មិនស្គាល់ទីលាន',
    booking_no_team: 'មិនមានក្រុម',
    booking_waiting_owner_approval: 'កំពុងរង់ចាំការយល់ព្រមពីម្ចាស់ទីលាន។ ម៉ោងនេះនៅតែបើករហូតដល់បានបញ្ជាក់។',
    booking_already_matched: 'បានផ្គូផ្គងរួចហើយ',
    booking_team_a: 'ក្រុម A',
    booking_cancelling_match: 'កំពុងបោះបង់ការប្រកួត...',
    booking_cancel_matched_opponent: 'បោះបង់គូប្រកួតដែលបានផ្គូផ្គង',
    booking_open_match: 'បើកការប្រកួត',
    booking_close_match: 'បិទការប្រកួត',
    booking_unknown_team: 'មិនស្គាល់ក្រុម',
    booking_unknown_captain: 'មិនស្គាល់ប្រធានក្រុម',
    booking_approve_join: 'យល់ព្រមឱ្យចូលរួម',
    booking_empty_title: 'មិនមានការកក់',
    booking_empty_create_first: 'បង្កើតការកក់ដំបូងរបស់អ្នកដើម្បីចាប់ផ្តើម។',
    booking_empty_request_captain: 'សូមស្នើសុំសិទ្ធិកាពីតែននៅក្នុងការកំណត់។',
    booking_empty_filtered: 'មិនមានការកក់សម្រាប់តម្រងដែលបានជ្រើសរើស។',
    team_captain: 'ប្រធានក្រុម',
    create_booking_access_required: 'ត្រូវការសិទ្ធិ',
    create_booking_access_description: 'អ្នកត្រូវការសិទ្ធិកាពីតែន ម្ចាស់ទីលាន ឬអ្នកគ្រប់គ្រង ដើម្បីកក់ទីលាន។',
    create_booking_title: 'បង្កើតការកក់ថ្មី',
    create_booking_subtitle: 'កក់ទីលានបាល់ទាត់សម្រាប់ក្រុមរបស់អ្នក',
    create_booking_select_field: 'ជ្រើសរើសទីលាន *',
    create_booking_select_team: 'ជ្រើសរើសក្រុម *',
    create_booking_choose_field: 'ជ្រើសរើសទីលាន...',
    create_booking_choose_team: 'ជ្រើសរើសក្រុម...',
    create_booking_jersey_colors: 'ពណ៌អាវក្រុម',
    create_booking_need_team: 'អ្នកត្រូវការក្រុមមួយមុនពេលកក់។',
    create_booking_start_time: 'ម៉ោងចាប់ផ្តើម *',
    create_booking_duration: 'រយៈពេល *',
    create_booking_notes: 'កំណត់ចំណាំ',
    create_booking_notes_placeholder: 'បន្ថែមកំណត់ចំណាំអំពីការកក់...',
    create_booking_summary: 'សង្ខេបការកក់',
    create_booking_field: 'ទីលាន',
    create_booking_team: 'ក្រុម',
    create_booking_date_time: 'កាលបរិច្ឆេទ និងម៉ោង',
    create_booking_total_price: 'តម្លៃសរុប',
    create_booking_field_details: 'ព័ត៌មានទីលានសម្រាប់កាពីតែន',
    create_booking_field_type: 'ប្រភេទទីលាន',
    create_booking_surface: 'ផ្ទៃ',
    create_booking_capacity: 'ចំណុះ',
    create_booking_amenities: 'សេវាកម្មបន្ថែម',
    create_booking_no_amenities: 'មិនមានសេវាកម្មបន្ថែមសម្រាប់ទីលាននេះទេ។',
    create_booking_submit: 'បង្កើតការកក់',
    create_booking_submitting: 'កំពុងបង្កើតការកក់...',
    create_booking_success: 'បានបង្កើតការកក់ដោយជោគជ័យ!',
    create_booking_valid_datetime: 'សូមបញ្ចូលកាលបរិច្ឆេទ និងម៉ោងឱ្យត្រឹមត្រូវ',
    field_not_found: 'រកមិនឃើញទីលាន',
    field_not_found_description: 'ទីលាននេះអាចត្រូវបានលុប ឬតំណភ្ជាប់មិនត្រឹមត្រូវ។',
    field_not_available: 'មិនអាចប្រើបាន',
    field_request_access: 'ស្នើសុំសិទ្ធិកក់',
    field_overview: 'ទិដ្ឋភាពទូទៅ',
    field_live_booking: 'ការកក់ផ្ទាល់',
    field_comment_rate: 'មតិយោបល់ និងវាយតម្លៃ',
    field_about: 'អំពីទីលាននេះ',
    field_ready_description: 'ទីលាននេះរួចរាល់សម្រាប់ការកក់ ការលេងជាក្រុម និងការប្រកួតជាប្រចាំ។',
    field_name: 'ឈ្មោះទីលាន',
    field_type: 'ប្រភេទទីលាន',
    field_surface_type: 'ប្រភេទផ្ទៃ',
    field_price_per_hour: 'តម្លៃក្នុងមួយម៉ោង',
    field_discount: 'បញ្ចុះតម្លៃ',
    field_capacity: 'ចំណុះ',
    field_status: 'ស្ថានភាព',
    field_full_address: 'អាសយដ្ឋានពេញ',
    field_address_not_specified: 'មិនបានបញ្ជាក់អាសយដ្ឋាន',
    field_coordinates: 'កូអរដោនេ៖ {{lat}}, {{lng}}',
    field_location_map: 'ផែនទីទីតាំង',
    field_amenities: 'សេវាកម្មបន្ថែម',
    field_live_schedule: 'កាលវិភាគកក់ផ្ទាល់',
    field_live_schedule_subtitle: 'កាលវិភាគសម្រាប់ទីលាននេះប៉ុណ្ណោះ។ មើលថានរណាកំពុងលេងនៅម៉ោងណា។',
    field_select_day: 'ជ្រើសរើសថ្ងៃ',
    field_schedule: 'កាលវិភាគទីលាន',
    field_schedule_subtitle: 'បង្ហាញតែទីលាននេះប៉ុណ្ណោះ។ កាពីតែនអាចកក់ម៉ោងទំនេរបាន។',
    field_available: 'ទំនេរ',
    field_booked: 'បានកក់',
    field_available_slot: 'ទំនេរ - ចុចដើម្បីកក់',
    field_available_open: 'អាចកក់បានលើទីលាននេះ។',
    field_reserved_slot: 'ម៉ោងបានកក់',
    field_pending_request: 'មានសំណើកំពុងរង់ចាំលើទីលាននេះ។',
    field_confirmed_booking: 'មានការកក់ដែលបានយល់ព្រមលើទីលាននេះ។',
    field_reviews_coming: 'ការវាយតម្លៃនឹងបង្ហាញនៅទីនេះ',
    field_reviews_placeholder: 'មតិយោបល់ និងការវាយតម្លៃអំពីទីលានអាចបង្ហាញនៅផ្នែកនេះ បន្ទាប់ពីភ្ជាប់ទិន្នន័យរួច។',
    not_specified: 'មិនបានបញ្ជាក់',
    players_suffix: '{{count}} នាក់',
    hour_suffix: '{{value}} ម៉ោង',
    hours_suffix: '{{value}} ម៉ោង',
    login_badge: 'ចូលប្រើគណនី',
    login_title: 'ចូលគណនី',
    login_description: 'សូមស្វាគមន៍មកវិញ។ ចូលគណនីដើម្បីបន្តគ្រប់គ្រងការកក់ ក្រុម និងសកម្មភាពបាល់ទាត់របស់អ្នក។',
    login_no_account: 'មិនទាន់មានគណនីមែនទេ?',
    login_create_one: 'បង្កើតនៅទីនេះ',
    login_email_label: 'អ៊ីមែល',
    login_password_label: 'ពាក្យសម្ងាត់',
    login_remember_me: 'ចងចាំខ្ញុំ',
    login_forgot_password: 'ភ្លេចពាក្យសម្ងាត់?',
    login_forgot_not_ready: 'មុខងារភ្លេចពាក្យសម្ងាត់មិនទាន់មាននៅឡើយទេ។',
    login_not_available_title: 'មិនទាន់អាចប្រើបាន',
    login_signing_in: 'កំពុងចូលគណនី...',
    login_browse_first: 'ចង់មើលសិនទេ?',
    login_continue_guest: 'បន្តជាភ្ញៀវ',
    login_validation_email: 'សូមបញ្ចូលអាសយដ្ឋានអ៊ីមែលរបស់អ្នក។',
    login_validation_password: 'សូមបញ្ចូលពាក្យសម្ងាត់របស់អ្នក។',
    register_badge: 'គណនីថ្មី',
    register_title: 'បង្កើតគណនី',
    register_description: 'បង្កើតគណនីរបស់អ្នកដើម្បីចាប់ផ្តើមកក់ទីលាន ចូលរួមក្រុម ឬគ្រប់គ្រងទីលានរបស់អ្នកបានយ៉ាងងាយស្រួល។',
    register_already_have_account: 'មានគណនីរួចហើយ?',
    register_sign_in: 'ចូលគណនី',
    register_first_name: 'នាមខ្លួន',
    register_last_name: 'នាមត្រកូល',
    register_username: 'ឈ្មោះអ្នកប្រើ',
    register_phone: 'ទូរស័ព្ទ',
    register_email: 'អ៊ីមែល',
    register_password: 'ពាក្យសម្ងាត់',
    register_confirm_password: 'បញ្ជាក់ពាក្យសម្ងាត់',
    register_password_hint: 'ប្រើយ៉ាងហោចណាស់ 8 តួអក្សរ។',
    register_update_later: 'អ្នកអាចកែប្រែប្រវត្តិរូបនៅពេលក្រោយបាន',
    register_creating: 'កំពុងបង្កើត...',
    register_validation_first_name: 'សូមបញ្ចូលនាមខ្លួនរបស់អ្នក។',
    register_validation_last_name: 'សូមបញ្ចូលនាមត្រកូលរបស់អ្នក។',
    register_validation_username: 'សូមបញ្ចូលឈ្មោះអ្នកប្រើរបស់អ្នក។',
    register_validation_email: 'សូមបញ្ចូលអាសយដ្ឋានអ៊ីមែលរបស់អ្នក។',
    register_validation_password: 'សូមបញ្ចូលពាក្យសម្ងាត់របស់អ្នក។',
    register_validation_confirm_password: 'សូមបញ្ជាក់ពាក្យសម្ងាត់របស់អ្នក។',
    register_passwords_no_match: 'ពាក្យសម្ងាត់មិនត្រូវគ្នា។',
    settings_account_center: 'មជ្ឈមណ្ឌលគណនី',
    settings_intro: 'ទំព័រនេះបានរៀបចំអ្វីៗដែលអ្នកប្រើប្រាស់ជាទូទៅរំពឹងទុកនៅក្នុងការកំណត់ ដូចជា ទិដ្ឋភាពគណនី ចំណូលចិត្តឧបករណ៍ សុវត្ថិភាព និងសំណើសិទ្ធិ។',
    settings_preferences: 'ចំណូលចិត្ត',
    settings_preferences_desc: 'ជម្រើសតូចៗដែលធ្វើឱ្យការប្រើប្រាស់កម្មវិធីមានលក្ខណៈផ្ទាល់ខ្លួនជាងមុន។ ទិន្នន័យទាំងនេះត្រូវបានរក្សាទុកលើឧបករណ៍នេះ។',
    settings_local_only: 'តែក្នុងឧបករណ៍នេះ',
    settings_email_updates: 'ការអាប់ដេតតាមអ៊ីមែល',
    settings_email_updates_desc: 'បើកទទួលការអាប់ដេតសំខាន់ៗនៃគណនី និងលទ្ធផលសំណើ។',
    settings_booking_reminders: 'ការរំលឹកការកក់',
    settings_booking_reminders_desc: 'បង្ហាញការរំលឹកសម្រាប់ការកក់ខាងមុខ និងការបញ្ជាក់ទីលានដែលកំពុងរង់ចាំ។',
    settings_match_alerts: 'ការជូនដំណឹងការប្រកួត និងការអញ្ជើញ',
    settings_match_alerts_desc: 'ផ្តល់អាទិភាពដល់ការអញ្ជើញក្រុម សំណើចូលរួម និងសកម្មភាពប្រកួតបើកចំហ។',
    settings_compact_layout: 'ប្លង់តូចជាប់គ្នា',
    settings_compact_layout_desc: 'ប្រើគម្លាតតូចជាងមុនសម្រាប់តារាង និងទំព័រដែលមានមាតិកាច្រើន។',
    settings_language_desc: 'ប្តូរភាសាផ្ទៃមុខសម្រាប់កម្មវិធីក្នុងកម្មវិធីរុករកនេះ។',
    settings_start_page: 'ទំព័រចាប់ផ្តើមលំនាំដើម',
    settings_start_page_desc: 'ជ្រើសតំបន់ដំបូងដែលអ្នកចង់ឃើញពេលបើកកម្មវិធី។',
    settings_access_requests: 'សំណើសុំសិទ្ធិ',
    settings_access_requests_desc: 'ដំឡើងសិទ្ធិគណនីរបស់អ្នក នៅពេលអ្នកត្រូវការតួនាទីបន្ថែម ដូចជា ការកក់ទីលាន ការគ្រប់គ្រងក្រុម ឬការគ្រប់គ្រងទីលាន។',
    settings_request_history: 'ប្រវត្តិសំណើ',
    settings_request_history_desc: 'បង្ហាញសង្ខេបលឿនអំពីសំណើសិទ្ធិចាស់ៗ និងស្ថានភាពពិនិត្យរបស់វា។',
    settings_security: 'សុវត្ថិភាព',
    settings_security_desc: 'រក្សាគណនីរបស់អ្នកឱ្យមានសុវត្ថិភាព និងពិនិត្យសកម្មភាពដែលពាក់ព័ន្ធនឹងការចូលគណនី។',
    settings_password: 'ពាក្យសម្ងាត់',
    settings_password_desc: 'ប្តូរពាក្យសម្ងាត់បានគ្រប់ពេល ប្រសិនបើអ្នកចែករំលែកឧបករណ៍ ប្រើពាក្យសម្ងាត់ចាស់ ឬចង់បានពាក្យសម្ងាត់ខ្លាំងជាងមុន។',
    settings_change_password: 'ប្តូរពាក្យសម្ងាត់',
    settings_current_account_role: 'តួនាទីគណនីបច្ចុប្បន្ន',
    settings_last_review: 'ការពិនិត្យការកំណត់ចុងក្រោយ',
    settings_quick_links: 'ផ្លូវកាត់រហ័ស',
    settings_quick_links_desc: 'សកម្មភាពផ្លូវកាត់ដែលមនុស្សភាគច្រើនតែងស្វែងរកពេលគ្រប់គ្រងគណនី។',
    settings_current_role: 'តួនាទីបច្ចុប្បន្ន',
    settings_captain_access: 'សិទ្ធិកាពីតែន',
    settings_captain_access_desc: 'បង្កើតការកក់ទីលាន គ្រប់គ្រងសមាជិកក្រុម អនុម័តសំណើចូលរួម និងរៀបចំការប្រកួតបើកចំហ។',
    settings_owner_access: 'សិទ្ធិម្ចាស់ទីលាន',
    settings_owner_access_desc: 'បង្កើតទីលាន គ្រប់គ្រងសំណើកក់ និងគ្រប់គ្រងកាលវិភាគទីលានរបស់អ្នក។',
    settings_member_since: 'ជាសមាជិកតាំងពី',
    settings_pending_requests: 'សំណើកំពុងរង់ចាំ',
    settings_available_upgrades: 'សិទ្ធិបន្ថែមដែលអាចស្នើបាន',
    settings_profile_details: 'ព័ត៌មានប្រវត្តិរូប',
    settings_profile_details_desc: 'ធ្វើបច្ចុប្បន្នភាពរូបភាព និងព័ត៌មានផ្ទាល់ខ្លួនរបស់អ្នក។',
    settings_notifications_desc: 'ពិនិត្យការអញ្ជើញ ការជូនដំណឹង និងព័ត៌មានថ្មីដែលមិនទាន់អាន។',
    settings_pending_review: 'កំពុងរង់ចាំពិនិត្យ',
    settings_request_again: 'ស្នើម្តងទៀត',
    settings_request_role_button: 'ស្នើ {{role}}',
    settings_submitting: 'កំពុងផ្ញើ...',
    settings_deleting: 'កំពុងលុប...',
    settings_delete_request: 'លុបសំណើ',
    settings_what_belongs: 'អ្វីដែលគួរមាននៅទីនេះ?',
    settings_what_belongs_desc: 'ជាទូទៅមាន សុវត្ថិភាព ការជូនដំណឹង ចំណូលចិត្តកម្មវិធី ការគាំទ្រ និងសំណើសុំតួនាទី ឬសិទ្ធិ។ ទំព័រនេះឥឡូវធ្វើតាមរចនាសម្ព័ន្ធនោះ។',
    settings_change_password_desc: 'បញ្ចូលពាក្យសម្ងាត់បច្ចុប្បន្នរបស់អ្នក ហើយជ្រើសពាក្យសម្ងាត់ថ្មីមួយ។',
    settings_close_password_form: 'បិទទម្រង់ប្តូរពាក្យសម្ងាត់',
    settings_current_password: 'ពាក្យសម្ងាត់បច្ចុប្បន្ន',
    settings_new_password: 'ពាក្យសម្ងាត់ថ្មី',
    settings_confirm_new_password: 'បញ្ជាក់ពាក្យសម្ងាត់ថ្មី',
    settings_hide_current_password: 'លាក់ពាក្យសម្ងាត់បច្ចុប្បន្ន',
    settings_show_current_password: 'បង្ហាញពាក្យសម្ងាត់បច្ចុប្បន្ន',
    settings_hide_new_password: 'លាក់ពាក្យសម្ងាត់ថ្មី',
    settings_show_new_password: 'បង្ហាញពាក្យសម្ងាត់ថ្មី',
    settings_hide_password_confirmation: 'លាក់ការបញ្ជាក់ពាក្យសម្ងាត់',
    settings_show_password_confirmation: 'បង្ហាញការបញ្ជាក់ពាក្យសម្ងាត់',
    settings_changing_password: 'កំពុងប្តូរ...',
    settings_save_password: 'រក្សាទុកពាក្យសម្ងាត់',
    profile_admin: 'ប្រវត្តិរូបអ្នកគ្រប់គ្រង',
    profile_owner: 'ប្រវត្តិរូបម្ចាស់ទីលាន',
    profile_account: 'ប្រវត្តិរូបគណនី',
    profile_unknown_user: 'មិនស្គាល់អ្នកប្រើ',
    profile_guest: 'ភ្ញៀវ',
    profile_edit: 'កែប្រែប្រវត្តិរូប',
    profile_remove_photo: 'លុបរូបភាព',
    profile_admin_tools: 'ឧបករណ៍អ្នកគ្រប់គ្រង',
    profile_admin_shortcuts: 'ផ្លូវកាត់គ្រប់គ្រង',
    profile_admin_shortcuts_desc: 'តំណភ្ជាប់រហ័សសម្រាប់តំបន់ដែលអ្នកគ្រប់គ្រងញឹកញាប់បំផុត។',
    profile_manage_users_desc: 'ពិនិត្យ និងគ្រប់គ្រងគណនីអ្នកប្រើ។',
    profile_role_requests_desc: 'អនុម័ត ឬបដិសេធការផ្លាស់ប្តូរសិទ្ធិ។',
    profile_account_status: 'ស្ថានភាពគណនី',
    profile_active: 'សកម្ម',
    profile_personal_info: 'ព័ត៌មានផ្ទាល់ខ្លួន',
    profile_full_name: 'ឈ្មោះពេញ',
    profile_not_specified: 'មិនបានបញ្ជាក់',
    profile_dob: 'ថ្ងៃខែឆ្នាំកំណើត',
    profile_address: 'អាសយដ្ឋាន',
    profile_account_stats: 'ស្ថិតិគណនី',
    profile_total_bookings: 'ការកក់សរុប',
    profile_current_teams: 'ក្រុមបច្ចុប្បន្ន',
    profile_no_teams: 'អ្នកមិនទាន់ស្ថិតក្នុងក្រុមណាមួយទេ។',
    profile_no_home_field: 'មិនទាន់កំណត់ទីលានផ្ទះ',
    profile_members_count: '{{count}} សមាជិក',
    profile_view_team: 'មើលក្រុម',
    profile_photo: 'រូបភាពប្រវត្តិរូប',
    profile_edit_message: 'ធ្វើបច្ចុប្បន្នភាពព័ត៌មានគណនីរបស់អ្នកខាងក្រោម។',
    profile_saving: 'កំពុងរក្សាទុក...',
    profile_save_changes: 'រក្សាទុកការផ្លាស់ប្តូរ',
    profile_enter_first_name: 'បញ្ចូលនាមខ្លួន',
    profile_enter_last_name: 'បញ្ចូលនាមត្រកូល',
    profile_enter_email: 'បញ្ចូលអ៊ីមែល',
    profile_phone_number: 'លេខទូរស័ព្ទ',
    profile_enter_phone: 'បញ្ចូលលេខទូរស័ព្ទ',
    profile_gender: 'ភេទ',
    profile_gender_male: 'ប្រុស',
    profile_gender_female: 'ស្រី',
    profile_gender_other: 'ផ្សេងទៀត',
    profile_enter_address: 'បញ្ចូលអាសយដ្ឋាន',
    teams_all: 'ក្រុមទាំងអស់',
    teams_my: 'ក្រុមរបស់ខ្ញុំ',
    teams_admin_desc: 'ទិដ្ឋភាពអ្នកគ្រប់គ្រងសម្រាប់ក្រុមទាំងអស់។ អ្នកអាចបើកមើល ឬលុបក្រុមណាមួយក៏បាន។',
    teams_my_desc: 'មើលក្រុមសកម្មរបស់អ្នក និងគ្រប់គ្រងសំណើសមាជិក ប្រសិនបើអ្នកជាកាពីតែន។',
    teams_results: '{{count}} លទ្ធផល',
    teams_browse: 'រកមើលក្រុម',
    teams_invitations: 'ការអញ្ជើញចូលក្រុម',
    teams_pending_count: '{{count}} កំពុងរង់ចាំ',
    teams_invited_by: 'បានអញ្ជើញដោយ: {{name}}',
    teams_captain: 'កាពីតែន',
    teams_accept: 'ទទួលយក',
    teams_decline: 'បដិសេធ',
    teams_no_description: 'មិនមានការពិពណ៌នា។',
    teams_captain_label: 'កាពីតែន: {{name}}',
    teams_home_field: 'ទីលានផ្ទះ: {{name}}',
    teams_skill: 'កម្រិត:',
    teams_jersey: 'អាវក្រុម:',
    teams_view_details: 'មើលព័ត៌មានលម្អិត',
    teams_delete: 'លុប',
    teams_none_found: 'រកមិនឃើញក្រុម',
    teams_none_found_desc: 'ស្វែងរកក្រុមដើម្បីស្នើចូលរួម ឬបង្កើតក្រុមផ្ទាល់ខ្លួន ប្រសិនបើអ្នកជាកាពីតែន។',
    teams_delete_modal_title: 'លុបក្រុម',
    teams_delete_modal_desc: 'ផ្ញើសារទៅកាពីតែន មុនពេលលុប {{team}}។',
    teams_message_to_captain: 'សារទៅកាពីតែន',
    teams_delete_reason_placeholder: 'ពន្យល់មូលហេតុដែលក្រុមនេះត្រូវបានលុប...',
    teams_send_delete: 'ផ្ញើ និងលុប',
    teams_image: 'រូបភាពក្រុម',
    league_title: 'លីគបាល់ទាត់',
    league_subtitle: 'ពិន្ទុផ្ទាល់ និងតារាងចំណាត់ថ្នាក់',
    league_table: 'តារាង',
    league_loading: 'កំពុងផ្ទុកទិន្នន័យលីគ...',
    league_yesterday: 'ម្សិលមិញ',
    league_today: 'ថ្ងៃនេះ',
    league_tomorrow: 'ស្អែក',
    league_latest_matches: 'ការប្រកួតចុងក្រោយ',
    league_no_matches_date: 'មិនមានការប្រកួតសម្រាប់ថ្ងៃនេះទេ។',
    league_table_title: 'តារាងលីគ',
    league_form: 'ទម្រង់',
    league_full_time: 'ចប់ការប្រកួត',
    league_live: 'កំពុងផ្សាយផ្ទាល់',
    league_postponed: 'ពន្យារពេល',
    league_upcoming: 'ខាងមុខ'
  }
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    try {
      return localStorage.getItem(LANGUAGE_STORAGE_KEY) || 'en';
    } catch {
      return 'en';
    }
  });

  const changeLanguage = (nextLanguage) => {
    const safe = nextLanguage === 'km' ? 'km' : 'en';
    setLanguage(safe);
    try {
      localStorage.setItem(LANGUAGE_STORAGE_KEY, safe);
    } catch {}
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const translate = (key, fallback, replacements = {}) => {
    const template = translations[language]?.[key] || fallback || key;
    return Object.entries(replacements).reduce(
      (result, [token, value]) => result.replaceAll(`{{${token}}}`, String(value)),
      template
    );
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage: changeLanguage,
      t: translate
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
