$kind: http-request
name: Get Payment Config
method: GET
url: '{{base_url}}/api/payments/config'
order: 1000
scripts:
  - type: afterResponse
    language: text/javascript
    code: |-
      pm.test("Status is 2xx", function () {
        pm.response.to.be.success;
      });
      pm.test("Response is JSON", function () {
        pm.response.to.be.json;
      });
